# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 62c0e8e132a7056f912c1ea6c6b2a71a2dbd5c02c617b0ae6e7aea4362a9e085fd5ac3a2a669577eff79f334bdf691001eebee37bd553598d330d372cfa3f884

test:
  secret_key_base: c5c26ecf35eadaefbccdb58ae1c46818ac22b92604b88d5c7252359de406d2f409d6e6c105501b5124dc596548db7660d5e37001162a207d2d8c21b746326032

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
